---
name: CI (branch)
# This workflow is triggered manually and can be used to test workflow changes on a branch (which aren't picked up by the pr-bot builds)

on:
  workflow_dispatch:
    inputs:
      prNumber:
        description: set to the PR number if testing a branch for a PR (used to derive the image tag)
        default: ''
        type: string
        required: false
      runFullTests:
        description: tick to run the full tests, untick to run tests without credentials
        default: true
        type: boolean
        required: false

permissions:
  contents: write
  packages: write

jobs:
  build-test-publish:
    name: "Build, test, publish"
    uses: ./.github/workflows/ci_common.yml
    with:
      release: false
      prNumber: ${{ github.event.inputs.prNumber }}
      # despite the runFullTests input being a boolean, we seem to get a string below!
      runFullTests: ${{ github.event.inputs.runFullTests == 'true' }}
    secrets:
      AZDO_TOKEN: ${{ secrets.AZDO_TOKEN }}
